stages:
  - test
  - build
  - validate
  - plan
  - deploy
  - destroy

.terraform:
  image:
    name: hashicorp/terraform:1.5.2
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  cache:
    - key:
        files:
          - ./terraform/.terraform.lock.hcl
      paths:
        - ./terraform/.terraform
  before_script:
    - apk update && apk upgrade
    - apk add python3 && apk add bash && apk add curl && apk add aws-cli
    - cd terraform
    - terraform init
  after_script:
    - cd ..

test:expressjs:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  script:
    - cd expressjs
    - npm i
    - npm run test
    - cd ..

test:nextjs:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  script:
    - cd nextjs
    - npm i
    - npm run test
    - cd ..

build:expressjs:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:expressjs
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  script:
    - apk update && apk upgrade
    - apk add bash && apk add zip
    - cd expressjs
    - npm i
    - npm run prepare-lambda
    - cd ..
  artifacts:
    paths:
      - expressjs/layer.zip
      - expressjs/source.zip

build:nextjs:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:nextjs
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
  script:
    - cd nextjs
    - npm i
    - npm run prepare-next
    - cd ..
  artifacts:
    paths:
      - nextjs/.next-tf

validate:
  needs:
    - build:expressjs
    - build:nextjs
  stage: validate
  extends: .terraform
  script:
    - terraform validate

plan:dev:
  needs:
    - build:expressjs
    - build:nextjs
    - validate
  stage: plan
  extends: .terraform
  script:
    - terraform workspace select dev
    - terraform plan -var-file=envs/dev.tfvars -out=tf-dev-plan
  artifacts:
    paths:
      - terraform/tf-dev-plan

deploy:dev:
  needs:
    - build:expressjs
    - build:nextjs
    - plan:dev
  stage: deploy
  extends: .terraform
  when: manual
  script:
    - terraform apply "tf-dev-plan"

plan:destroy:dev:
  needs:
    - build:expressjs
    - build:nextjs
    - validate
  stage: destroy
  extends: .terraform
  when: manual
  script:
    - terraform workspace select dev
    - terraform plan -var-file=envs/dev.tfvars -out=tf-destroy-dev-plan -destroy
  artifacts:
    paths:
      - terraform/tf-destroy-dev-plan

destroy:dev:
  needs:
    - build:expressjs
    - build:nextjs
    - plan:destroy:dev
  stage: destroy
  extends: .terraform
  when: manual
  script:
    - terraform apply "tf-destroy-dev-plan"
