stages:
  - test
  - build
  - validate
  - plan
  - deploy
  - destroy

.terraform:
  image:
    name: hashicorp/terraform:1.5.2
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  cache:
    - key:
        files:
          - ./terraform/.terraform.lock.hcl
      paths:
        - ./terraform/.terraform
  before_script:
    - apk update && apk upgrade
    - apk add python3 && apk add bash && apk add curl && apk add aws-cli
    - cd terraform
    - terraform init
  after_script:
    - cd ..

test:expressjs:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - expressjs/package-lock.json
      paths:
        - expressjs/node_modules
  script:
    - cd expressjs
    - npm i
    - npm run test
    - cd ..

test:nextjs-v12:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - nextjs-v12/package-lock.json
      paths:
        - nextjs-v12/node_modules
  script:
    - cd nextjs-v12
    - npm i
    - npm run test
    - cd ..

test:nextjs-v14-static:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - nextjs-v14-static/package-lock.json
      paths:
        - nextjs-v14-static/node_modules
  script:
    - cd nextjs-v14-static
    - npm i
    - npm run test
    - cd ..

test:reactjs:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - reactjs/package-lock.json
      paths:
        - reactjs/node_modules
  script:
    - cd reactjs
    - npm i
    - npm run test
    - cd ..

test:vuejs:
  stage: test
  image: node:18-alpine3.17
  cache:
    - key:
        files:
          - vuejs/package-lock.json
      paths:
        - vuejs/node_modules
  script:
    - cd vuejs
    - npm i
    - npm run test
    - cd ..

build:expressjs:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:expressjs
  cache:
    - key:
        files:
          - expressjs/package-lock.json
      paths:
        - expressjs/node_modules
  script:
    - apk update && apk upgrade
    - apk add bash && apk add zip
    - cd expressjs
    - npm i
    - npm run prepare-lambda
    - cd ..
  artifacts:
    paths:
      - expressjs/layer.zip
      - expressjs/source.zip

build:nextjs-v12:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:nextjs-v12
  cache:
    - key:
        files:
          - nextjs-v12/package-lock.json
      paths:
        - nextjs-v12/node_modules
  script:
    - cd nextjs-v12
    - npm i
    - npm run prepare-next
    - cd ..
  artifacts:
    paths:
      - nextjs-v12/.next-tf

build:nextjs-v14-static:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:nextjs-v14-static
  cache:
    - key:
        files:
          - nextjs-v14-static/package-lock.json
      paths:
        - nextjs-v14-static/node_modules
  script:
    - cd nextjs-v14-static
    - npm i
    - npm run build
    - cd ..
  artifacts:
    paths:
      - nextjs-v14-static/build

build:reactjs:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:reactjs
  cache:
    - key:
        files:
          - reactjs/package-lock.json
      paths:
        - reactjs/node_modules
  script:
    - cd reactjs
    - npm i
    - CI=false npm run build
    - cd ..
  artifacts:
    paths:
      - reactjs/build

build:vuejs:
  stage: build
  image: node:18-alpine3.17
  needs:
    - test:vuejs
  cache:
    - key:
        files:
          - vuejs/package-lock.json
      paths:
        - vuejs/node_modules
  script:
    - cd vuejs
    - npm i
    - npm run build
    - cd ..
  artifacts:
    paths:
      - vuejs/build

validate:
  needs:
    - build:expressjs
    - build:nextjs-v12
    - build:nextjs-v14-static
    - build:reactjs
    - build:vuejs
  stage: validate
  extends: .terraform
  script:
    - terraform validate

visualize:
  needs:
    - validate
  stage: plan
  extends: .terraform
  script:
    - apk add graphviz
    - cd visualize
    - bash gen-visual.sh
    - cd ..
  artifacts:
    paths:
      - terraform/visualize

plan:dev:
  needs:
    - build:expressjs
    - build:nextjs-v12
    - build:nextjs-v14-static
    - build:reactjs
    - build:vuejs
    - validate
  stage: plan
  extends: .terraform
  script:
    - terraform workspace select dev
    - terraform plan -var-file=envs/dev.tfvars -out=tf-dev-plan
  artifacts:
    paths:
      - terraform/tf-dev-plan

deploy:dev:
  needs:
    - build:expressjs
    - build:nextjs-v12
    - build:nextjs-v14-static
    - build:reactjs
    - build:vuejs
    - plan:dev
  stage: deploy
  extends: .terraform
  when: manual
  script:
    - terraform apply "tf-dev-plan"

plan:destroy:dev:
  needs:
    - build:expressjs
    - build:nextjs-v12
    - build:nextjs-v14-static
    - build:reactjs
    - build:vuejs
    - validate
  stage: destroy
  extends: .terraform
  when: manual
  script:
    - terraform workspace select dev
    - terraform plan -var-file=envs/dev.tfvars -out=tf-destroy-dev-plan -destroy
  artifacts:
    paths:
      - terraform/tf-destroy-dev-plan

destroy:dev:
  needs:
    - build:expressjs
    - build:nextjs-v12
    - build:nextjs-v14-static
    - build:reactjs
    - build:vuejs
    - plan:destroy:dev
  stage: destroy
  extends: .terraform
  when: manual
  script:
    - terraform apply "tf-destroy-dev-plan"
