name: CI/CD Pipeline

on:
  push:
    branches: ['main']

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  test-expressjs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: expressjs/package-lock.json
      - run: |
          cd expressjs
          npm ci
          npm run test

  test-expressjs-terraform:
    container:
      image: aquasec/trivy@sha256:be1190afcb28352bfddc4ddeb71470835d16462af68d310f9f4bca710961a41e # v0.70
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run Trivy IaC Scanner
        run: trivy config expressjs/terraform --severity CRITICAL --exit-code 1

  build-expressjs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: expressjs/package-lock.json
      - name: Install Zip
        run: sudo apt-get update && sudo apt-get install -y zip
      - run: |
          cd expressjs
          npm ci
          npm run prepare-lambda
      - uses: actions/upload-artifact@v6
        with:
          name: expressjs-artifacts
          path: |
            expressjs/layer.zip
            expressjs/source.zip

  deploy-dev-expressjs:
    needs:
      - test-expressjs
      - build-expressjs
      - test-expressjs-terraform
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.11.1

      - name: Download Artifacts - expressjs
        uses: actions/download-artifact@v7
        with:
          name: expressjs-artifacts
          path: expressjs

      - name: Deploy
        working-directory: expressjs/terraform
        env:
          TF_WORKSPACE: dev
        run: |
          terraform init
          terraform apply -auto-approve -var-file=config/dev.tfvars

  fetch-reactjs-config:
    needs:
      - deploy-dev-expressjs
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.11.1

      - name: Fetch ReactJS Config
        working-directory: scripts
        env:
          TF_WORKSPACE: dev
        run: |
          terraform init
          terraform apply -auto-approve -var-file=../reactjs/terraform/config/dev.tfvars

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: reactjs-env-artifact
          path: scripts/reactjs.env

  test-reactjs-terraform:
    needs:
      - fetch-reactjs-config
    container:
      image: aquasec/trivy@sha256:be1190afcb28352bfddc4ddeb71470835d16462af68d310f9f4bca710961a41e # v0.70
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run Trivy IaC Scanner
        run: trivy config reactjs/terraform --severity CRITICAL --exit-code 1

  test-reactjs:
    needs:
      - fetch-reactjs-config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json
      - run: |
          cd reactjs
          npm ci
          npm run test

  build-reactjs:
    needs:
      - fetch-reactjs-config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: reactjs/package-lock.json

      - name: Download Config Artifact
        uses: actions/download-artifact@v7
        with:
          name: reactjs-env-artifact
          path: scripts

      - run: |
          cd reactjs
          npm ci
          cp ../scripts/reactjs.env .env
          CI=false npm run build
      - uses: actions/upload-artifact@v6
        with:
          name: reactjs-artifacts
          path: reactjs/build

  deploy-dev-reactjs:
    needs:
      - test-reactjs-terraform
      - test-reactjs
      - build-reactjs
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.11.1

      - name: Download Artifacts - reactjs
        uses: actions/download-artifact@v7
        with:
          name: reactjs-artifacts
          path: reactjs/build

      - name: Deploy
        working-directory: reactjs/terraform
        env:
          TF_WORKSPACE: dev
        run: |
          terraform init
          terraform apply -auto-approve -var-file=config/dev.tfvars